FROM golang:alpine AS builder
WORKDIR $GOPATH/src/bradford-hamilton/slice-it-api

# Pull environment variables from the --build-args
ARG SLICE_IT_API_SERVER_PORT
ARG SLICE_IT_API_DB_HOST
ARG SLICE_IT_API_DB_PORT
ARG SLICE_IT_API_DB_USER
ARG SLICE_IT_API_DB_PASSWORD
ARG SLICE_IT_API_DB_NAME
ARG SLICE_IT_API_SSL_MODE
ARG SLICE_IT_ENVIRONMENT

# Set env vars
ENV SLICE_IT_API_SERVER_PORT=$SLICE_IT_API_SERVER_PORT
ENV SLICE_IT_API_DB_HOST=$SLICE_IT_API_DB_HOST
ENV SLICE_IT_API_DB_PORT=$SLICE_IT_API_DB_PORT
ENV SLICE_IT_API_DB_USER=$SLICE_IT_API_DB_USER
ENV SLICE_IT_API_DB_PASSWORD=$SLICE_IT_API_DB_PASSWORD
ENV SLICE_IT_API_DB_NAME=$SLICE_IT_API_DB_NAME
ENV SLICE_IT_API_SSL_MODE=$SLICE_IT_API_SSL_MODE
ENV SLICE_IT_ENVIRONMENT=$SLICE_IT_ENVIRONMENT

# Copy src code into image, fetch dependencies
COPY . .
RUN go mod download
WORKDIR $GOPATH/src/bradford-hamilton/slice-it-api/cmd/server

# Build for linux 64 bit
RUN GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o /go/bin/server .
EXPOSE 4000
ENTRYPOINT ["/go/bin/server"]
